# Generated by Django 5.0.2 on 2024-09-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('room_type', models.CharField(choices=[('Single', 'Single Room'), ('Double', 'Double Room'), ('Suite', 'Suite Room'), ('Deluxe', 'Deluxe Room')], max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
