# Generated by Django 5.0.2 on 2024-10-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omkar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_name', models.CharField(max_length=1000)),
                ('Room_amount', models.IntegerField()),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Adults', models.IntegerField()),
                ('Child', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Family_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_name', models.CharField(max_length=1000)),
                ('Room_amount', models.IntegerField()),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Adults', models.IntegerField()),
                ('Child', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_name', models.CharField(max_length=1000)),
                ('Room_amount', models.IntegerField()),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Adults', models.IntegerField()),
                ('Child', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Six_Bed_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_name', models.CharField(max_length=1000)),
                ('Room_amount', models.IntegerField()),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Adults', models.IntegerField()),
                ('Child', models.IntegerField()),
            ],
        ),
    ]
